[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "gen-crawler-ui"
dependencies = [
    'django-cors-headers == 4.3.1',
    'django-filter == 24.2',
    'djangorestframework == 3.15.1',
    'pip-chill == 1.0.3',
    'pylint-django == 2.5.5',
    'pytest == 8.2.2',
    'scrapy == 2.11.2',
]
authors = [{name = "Jason Mansour", email = "jason.mansour@gwdg.de"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
requires-python = ">= 3.10"