import { Crawler } from "./apitypes";

export const crawlerList: Crawler[] = [
  {
    id: 1,
    name: "Wikipedia",
    simple_state: "draft",
    state: "EXPLORATION_REQUIRED",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    source_item: "source-1",
    start_url: "https://de.wikipedia.org/wiki/Wikipedia:Hauptseite",
    inherited_fields: [],
    crawl_jobs: [],
    url: "", filter_set_id: null, filter_set_url: null,
  },
  {
    id: 2,
    name: "Leifi Physik",
    simple_state: "running",
    state: "EXPLORATION_RUNNING",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    source_item: "source-2",
    start_url: "https://www.leifiphysik.de/",
    inherited_fields: [],
    crawl_jobs: [],
    url: "", filter_set_id: null, filter_set_url: null,
  },
  {
    id: 3,
    name: "Klexikon",
    simple_state: "idle",
    state: "READY_FOR_CONTENT_CRAWL",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    source_item: "source-3",
    start_url: "https://klexikon.zum.de/",
    inherited_fields: [],
    crawl_jobs: [],
    url: "", filter_set_id: null, filter_set_url: null,
  },
  {
    id: 4,
    name: "Arbeitsagentur",
    simple_state: "error",
    state: "EXPLORATION_REQUIRED_JOB_FAILED",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    source_item: "source-4",
    start_url: "https://www.arbeitsagentur.de/",
    inherited_fields: [],
    crawl_jobs: [],
    url: "", filter_set_id: null, filter_set_url: null,
  },
  {
    id: 5,
    name: "Physik im Advent",
    simple_state: "error",
    state: "READY_FOR_CONTENT_CRAWL_JOB_FAILED",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    source_item: "source-5",
    start_url: "https://www.physik-im-advent.de/",
    inherited_fields: [],
    crawl_jobs: [],
    url: "", filter_set_id: null, filter_set_url: null,
  },
];
