# Generated by Django 5.0.6 on 2025-01-31 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0006_filterset_remaining_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedCrawlJob',
            fields=[
                ('crawljob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawls.crawljob')),
            ],
            bases=('crawls.crawljob',),
        ),
        migrations.AddField(
            model_name='crawledurl',
            name='noindex',
            field=models.BooleanField(default=False),
        ),
    ]
