# Generated by Django 5.0.6 on 2025-01-31 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0007_annotatedcrawljob_crawledurl_noindex'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crawledurl',
            unique_together={('crawl_job', 'url')},
        ),
    ]
