# Generated by Django 5.0.6 on 2025-10-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0008_alter_crawledurl_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_url', models.URLField()),
                ('source_item', models.CharField(max_length=255)),
            ],
        ),
    ]
