# Generated by Django 5.0.6 on 2025-10-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0010_sourceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawler',
            name='inherited_fields',
            field=models.JSONField(default=list),
        ),
    ]
