# Generated by Django 5.0.6 on 2025-10-31 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0011_crawler_inherited_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='crawler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_jobs', to='crawls.crawler'),
            preserve_default=False,
        ),
    ]
