# Generated by Django 5.0.6 on 2025-11-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0012_crawljob_crawler'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
