# Generated by Django 5.2.7 on 2025-11-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0013_crawljob_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterset',
            name='crawl_job',
        ),
        migrations.AddField(
            model_name='filterset',
            name='crawler',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_set', to='crawls.crawler'),
        ),
    ]
