# Generated by Django 5.2.7 on 2025-11-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0014_remove_filterset_crawl_job_filterset_crawler'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='scrapy_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
