# Generated by Django 5.2.7 on 2026-01-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0015_crawljob_scrapy_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='crawl_type',
            field=models.CharField(choices=[('EXPLORATION', 'Exploration'), ('CONTENT', 'Content')], default='EXPLORATION', max_length=20),
        ),
    ]
