# Generated by Django 5.2.7 on 2026-02-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0016_crawljob_crawl_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
