# Generated by Django 5.2.7 on 2026-02-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0017_sourceitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawljob',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20),
        ),
    ]
