# Generated by Django 5.2.7 on 2026-02-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0018_add_canceled_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='urls_processed',
            field=models.IntegerField(default=0),
        ),
    ]
