apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generic-crawler
  template:
    metadata:
      labels:
        app: generic-crawler
    spec:

      containers:
        - name: web
          image: jdmansour/generic-crawler-web:main
          env:
            - name: DB_PATH
              value: /app/database/db.sqlite3
            - name: SCRAPYD_URL
              value: http://scrapyd:6800
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /app/database
              name: sharedStorage
          command: >
            sh -c "python manage.py migrate &&
                   gunicorn crawler_ui.wsgi --bind 0.0.0.0:8000"
        - name: scrapyd
          image: jdmansour/generic-crawler-scrapyd:main
          env:
            - name: ARGS
              value: ""
            - name: DB_PATH
              value: /app/database/db.sqlite3
            - name: EDU_SHARING_BASE_URL
              value: https://repository.staging.openeduhub.net/edu-sharing/
            - name: EDU_SHARING_PASSWORD
              value: xxxxx
            - name: EDU_SHARING_USERNAME
              value: xxxxx
            - name: GENERIC_CRAWLER_DB_PATH
              value: /app/database/db.sqlite3
            - name: GENERIC_CRAWLER_LLM_API_KEY
              value: xxxxx
            - name: GENERIC_CRAWLER_USE_LLM_API
              value: "True"
            - name: LOG_LEVEL
              value: INFO
            - name: MODE
              value: edu-sharing
            - name: PLAYWRIGHT_WS_ENDPOINT
              value: ws://headless_chrome:3000
            - name: SPLASH_URL
              value: http://splash:8050
            - name: Z_API_KEY
              value: fASDBg3as#fASFjk
          ports:
            - containerPort: 6800
          volumeMounts:
            - mountPath: /app/database
              name: sharedStorage

      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: generic-crawler-service
spec:
  selector:
    app: generic-crawler
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
